import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import '../styles/typography.css';
import '../styles/mobile.css';
import NavBar from '../components/NavBar';
import MobileNavBar from '../components/MobileNavBar';
import PageTransitionWrapper from '../components/PageTransitionWrapper';

export const metadata: Metadata = {
  title: "Santelle | To Her Health",
  description: "Generated by create next app",
  icons: {
    icon: '/S_logo.svg',
    shortcut: '/S_logo.svg',
    apple: '/S_logo.svg',
  },
  viewport: {
    width: 'device-width',
    initialScale: 1,
    maximumScale: 1,
    userScalable: false,
    viewportFit: 'cover',
  },
};

const poppins = Poppins({ subsets: ['latin'], weight: ['300', '400', '500', '600', '700'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.className}>
      <head>
        <title>Santelle | To Her Health</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="theme-color" content="transparent" />
        <meta name="msapplication-navbutton-color" content="transparent" />
        <meta name="apple-mobile-web-app-title" content="Santelle" />
      </head>
      <body className={`antialiased`}>
        {/* Desktop Navigation */}
        <div className="hidden md:block">
          <NavBar />
        </div>
        
        {/* Mobile Navigation */}
        <div className="block md:hidden">
          <MobileNavBar />
        </div>
        
        <PageTransitionWrapper>{children}</PageTransitionWrapper>
      </body>
    </html>
  );
}
